### ISSUE TITLE
Doc: MediumMotor -> error in example

### ISSUE THREAD

**Issue by Splashcom** [lutzthies/robolab-docs-issue-tracker#6]
command: `motor.duty_cycle_sp = 200` 

Error message: `Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/ev3dev/core.py", line 455, in duty_cycle_sp
    self._duty_cycle_sp = self.set_attr_int(self._duty_cycle_sp, 'duty_cycle_sp', value)
  File "/usr/local/lib/python3.6/dist-packages/ev3dev/core.py", line 217, in set_attr_int
    return self._set_attribute(attribute, name, str(int(value)))
  File "/usr/local/lib/python3.6/dist-packages/ev3dev/core.py", line 206, in _set_attribute
    attribute.write(value.encode())
OSError: [Errno 22] Invalid argument`

new range (after python-ev3dev update): -100 to 100

**Comment by Splashcom** [comment]
fixed!
